### ISSUE TITLE
[Feat] Make a route number selection view

### ISSUE THREAD

**Issue by shwoghk14** [DeveloperAcademy-POSTECH/WidgetBus#14]
## 💡 Issue
정류장 기반 버스 번호 선택하는 뷰를 만듭니다.

## 📝  Todo

- [x] API 통신으로 정류장에 도착하는 버스 번호 받기.
- [x] 받은 버스 번호로 테이블 뷰 그리기.
- [x] 선택된 항목 백그라운드 색깔 표시하기.
