### ISSUE TITLE
Checklist before release

### ISSUE THREAD

**Issue by minjae9610** [DeveloperAcademy-POSTECH/WidgetBus#70]
## 💡 Issue

릴리즈 전 체크리스트

## 📝  Todo

- [ ] 회전 방향 설정
- [ ] 다크모드 비활성 설정
- [ ] 생각나는거 바로바로 추가해주세요
